// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/63fddd7c98d6b65891a5fd7c
###
GET http://localhost:8080/contacts/63fddd9098d6b65891a6141e
###
GET http://localhost:8080/contacts/63fddda998d6b65891a62f2f

// PRODUCTION Deploy
###
GET https://cse341-instructor.herokuapp.com/contacts
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4
